name: rsudp
channels:
  - defaults
  - rpi
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - numpy
  - future
  - scipy
  - lxml
  - sqlalchemy
  - obspy
  - pip:
    - aiohttp
    - async-timeout
    - attrs
    - multidict
    - oauthlib
    - pydub
    - requests-oauthlib
    - telepot
    - twython
    - urllib3
    - yarl
    - rsudp